CREATE DATABASE retail_analysis;

USE retail_analysis;


CREATE TABLE sales_data (
    `Row ID` INT,
    `Order ID` VARCHAR(50),
    `Order Date` DATE,
    `Ship Date` DATE,
    `Ship Mode` VARCHAR(50),
    `Customer ID` VARCHAR(50),
    `Customer Name` VARCHAR(100),
    Segment VARCHAR(50),
    Country VARCHAR(50),
    City VARCHAR(50),
    State VARCHAR(50),
    `Postal Code` VARCHAR(20),
    Region VARCHAR(50),
    `Product ID` VARCHAR(50),
    Category VARCHAR(50),
    `Sub Category` VARCHAR(50),
    `Product Name` TEXT,
    Sales FLOAT,
    Quantity INT,
    Discount DECIMAL(5,2),
    Profit FLOAT,
    `Profit Margin` DECIMAL(5,2),
    `Order Year` INT,
    `Order Month` TINYINT
);


select * from sales_data;

DESCRIBE sales_data;

-- 1.Total Sales

select SUM(Sales) as Total_sales
from sales_data;


--  2. What is the total revenue generated by each product category?

SELECT 
    Category,
    SUM(Sales) AS Total_Revenue
FROM sales_data
GROUP BY 
Category
ORDER BY 
Total_Revenue DESC;



-- 3. What is the average order value (AOV)?

SELECT 
    SUM(Sales) / COUNT(DISTINCT `Order ID`) AS Average_Order_Value
FROM sales_data;



-- 4. Find customers whose total sales are greater than overall average Customer sales.

SELECT `Customer ID`, SUM(Sales) AS Total_Sales
FROM sales_data
GROUP BY `Customer ID`
HAVING 
SUM(Sales) > (
    SELECT AVG(customer_total)
    FROM (
        SELECT SUM(Sales) AS customer_total
        FROM sales_data
        GROUP BY `Customer ID`
    ) avg_table
);


-- 5. Find customers who placed multiple orders on same date
SELECT 
    a.`Customer ID`,
    a.`Order Date`,
    COUNT(*) AS Orders_Count
FROM sales_data a
JOIN 
sales_data b
    ON a.`Customer ID` = b.`Customer ID`
    AND a.`Order Date` = b.`Order Date`
GROUP BY
 a.`Customer ID`, a.`Order Date`
HAVING COUNT(*) > 1;



-- 6. Find customers who made repeat purchases?

SELECT DISTINCT
    a.`Customer ID`,
    a.`Order ID` AS First_Order,
    b.`Order ID` AS Later_Order
FROM sales_data a
JOIN sales_data b
    ON a.`Customer ID` = b.`Customer ID`
    AND a.`Order Date` < b.`Order Date`;


    
-- 7. Rank Customers Based on Their Total Sales Revenue.
SELECT 
    `Customer ID`,
    SUM(Sales) AS Total_Sales,
    RANK() OVER (
    ORDER BY 
    SUM(Sales) DESC) AS Sales_Rank
FROM sales_data
GROUP BY `Customer ID`;



-- 8. Identify the top 3 highest revenue-generating customers within each region.
SELECT *
FROM (
    SELECT 
        Region,
        `Customer ID`,
        SUM(Sales) AS Total_Sales,
        RANK() OVER (PARTITION BY Region ORDER BY SUM(Sales) DESC
        ) AS Rank_In_Region
    FROM sales_data
    GROUP BY
    Region, `Customer ID`
) ranked
WHERE Rank_In_Region <= 3;


-- 9. Perform Year-over-Year revenue analysis to evaluate business growth trends over time. 
SELECT 
    `Order Year`,
    SUM(Sales) AS Yearly_Sales,
    LAG(SUM(Sales)) OVER (ORDER BY `Order Year`) AS Previous_Year,
    SUM(Sales) - LAG(SUM(Sales)) OVER (ORDER BY `Order Year`) AS Growth
FROM sales_data
GROUP BY `Order Year`;